const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const WITHDRAW = 'WITHDRAW';
const DEPOSIT = 'DEPOSIT';

export {INCREMENT, DECREMENT, LOGIN, LOGOUT, WITHDRAW, DEPOSIT}